import {describe,expect,it,vi} from 'vitest';
import {TableAudioPlayer} from '@/components/mahjong/table-audio';
import type {TableSoundEvent} from '@/components/mahjong/table-sounds';
const cue=(id='one'):TableSoundEvent=>({id,kind:'discard',seat:0});
function context(){
 const sources:Array<{buffer:unknown;onended:(()=>void)|null;connect:ReturnType<typeof vi.fn>;disconnect:ReturnType<typeof vi.fn>;start:ReturnType<typeof vi.fn>;stop:ReturnType<typeof vi.fn>}>=[];
 const ctx={state:'suspended',sampleRate:48000,currentTime:0,destination:{},resume:vi.fn(async()=>{ctx.state='running';}),suspend:vi.fn(async()=>{ctx.state='suspended';}),close:vi.fn(async()=>{ctx.state='closed';}),createGain:vi.fn(()=>({gain:{value:0},connect:vi.fn(),disconnect:vi.fn()})),createBuffer:vi.fn((_c:number,n:number)=>({getChannelData:()=>new Float32Array(n)})),createBufferSource:vi.fn(()=>{const s={buffer:null as unknown,onended:null as (()=>void)|null,connect:vi.fn(),disconnect:vi.fn(),start:vi.fn(),stop:vi.fn()};sources.push(s);return s;})};
 return {ctx,sources,create:vi.fn(()=>ctx as unknown as AudioContext)};
}
describe('finite table audio lifecycle',()=>{
 it('does not create a context or queue sounds before a gesture unlock',()=>{const f=context(),p=new TableAudioPlayer(f.create);expect(p.play(cue())).toBe(false);expect(f.create).not.toHaveBeenCalled();expect(f.sources).toHaveLength(0);});
 it('plays a live cue once and releases the completed node',async()=>{const f=context(),p=new TableAudioPlayer(f.create);expect(await p.unlock()).toBe(true);expect(p.play(cue())).toBe(true);expect(p.play(cue())).toBe(false);expect(f.sources).toHaveLength(1);f.sources[0].onended!();expect(f.sources[0].disconnect).toHaveBeenCalled();await p.dispose();expect(f.sources[0].stop).not.toHaveBeenCalled();});
 it('does not replay a discarded locked cue when unlocking later',async()=>{const f=context(),p=new TableAudioPlayer(f.create);p.play(cue());await p.unlock();expect(p.play(cue())).toBe(false);expect(p.play(cue('new'))).toBe(true);});
 it('mute immediately stops sound, does not queue and requires a new unlock',async()=>{const f=context(),p=new TableAudioPlayer(f.create);await p.unlock();p.play(cue());p.setEnabled(false);expect(f.sources[0].stop).toHaveBeenCalledOnce();expect(p.play(cue('muted'))).toBe(false);p.setEnabled(true);expect(p.play(cue('still-locked'))).toBe(false);await p.unlock();expect(p.play(cue('muted'))).toBe(false);expect(p.play(cue('live'))).toBe(true);});
 it('background pause stops sound and drops intervening cues',async()=>{const f=context(),p=new TableAudioPlayer(f.create);await p.unlock();p.play(cue());p.pause();expect(f.sources[0].stop).toHaveBeenCalledOnce();expect(p.play(cue('away'))).toBe(false);await p.unlock();expect(p.play(cue('away'))).toBe(false);expect(p.play(cue('returned'))).toBe(true);});
 it('unmount closes the context and cannot reopen it',async()=>{const f=context(),p=new TableAudioPlayer(f.create);await p.unlock();p.play(cue());await p.dispose();expect(f.sources[0].stop).toHaveBeenCalledOnce();expect(f.ctx.close).toHaveBeenCalledOnce();expect(await p.unlock()).toBe(false);expect(p.play(cue('late'))).toBe(false);expect(f.create).toHaveBeenCalledOnce();});
 it('handles denied browser permission without throwing or repeatedly creating contexts',async()=>{const f=context();f.ctx.resume.mockRejectedValue(new Error('NotAllowedError'));const p=new TableAudioPlayer(f.create);expect(await p.unlock()).toBe(false);expect(p.play(cue())).toBe(false);expect(await p.unlock()).toBe(false);expect(f.create).toHaveBeenCalledOnce();});
 it('cannot reactivate after disposal while resume is pending',async()=>{const f=context();let resolve!:()=>void;f.ctx.resume.mockImplementation(()=>new Promise<void>(r=>{resolve=r;}));const p=new TableAudioPlayer(f.create),permission=p.unlock();expect(resolve).toBeTypeOf('function');await p.dispose();f.ctx.state='running';resolve();expect(await permission).toBe(false);expect(p.play(cue())).toBe(false);});
 it('caps overlapping source nodes and caches the original wave buffer',async()=>{const f=context(),p=new TableAudioPlayer(f.create);await p.unlock();for(let n=0;n<12;n++)p.play(cue(String(n)));expect(f.sources.filter(s=>!s.stop.mock.calls.length)).toHaveLength(8);expect(f.ctx.createBuffer).toHaveBeenCalledOnce();await p.dispose();expect(f.sources.every(s=>s.disconnect.mock.calls.length>0)).toBe(true);});
});

it('a new hand cancels sources while preserving the already unlocked context',async()=>{const f=context(),p=new TableAudioPlayer(f.create);await p.unlock();p.play(cue());expect(p.cancel).toBeTypeOf('function');p.cancel();expect(f.sources[0].stop).toHaveBeenCalledOnce();expect(p.play(cue('new-hand'))).toBe(true);expect(f.ctx.suspend).not.toHaveBeenCalled();});

it('disposal closes directly without queuing another suspension',async()=>{const f=context(),p=new TableAudioPlayer(f.create);await p.unlock();p.setEnabled(false);expect(f.ctx.suspend).toHaveBeenCalledOnce();await p.dispose();expect(f.ctx.suspend).toHaveBeenCalledOnce();expect(f.ctx.close).toHaveBeenCalledOnce();});

it('awaits an in-flight suspension before closing so WebKit cannot restore suspended state afterward',async()=>{const f=context();let finish!:()=>void;f.ctx.suspend.mockImplementation(()=>new Promise<void>(resolve=>{finish=()=>{f.ctx.state='suspended';resolve();};}));const p=new TableAudioPlayer(f.create);await p.unlock();p.setEnabled(false);const closing=p.dispose();expect(f.ctx.close).not.toHaveBeenCalled();finish();await closing;expect(f.ctx.state).toBe('closed');expect(f.ctx.close).toHaveBeenCalledOnce();});
