import {describe,expect,it} from 'vitest';
import {acceptedPublicCallEvent} from '@/components/mahjong/public-call-motion';
import type {RoomView} from '@/modules/mahjong/types';
function pair(meld='p550-',variant:'yonma'|'sanma'='yonma') {
 const before={id:'r',variant,mode:'east',status:'playing',version:1,mySeat:0,game:{gameInstanceId:'g',handId:1,decisionId:'a',phase:'dapai',turnSeat:0,settlement:null,players:Array.from({length:variant==='sanma'?3:4},(_,seat)=>({seat,melds:[],discards:seat===0?['p0']:[],nuki:0}))}} as unknown as RoomView;
 const after=structuredClone(before);after.version++;after.game!.decisionId='b';after.game!.phase=meld.match(/\d/g)!.length===4?'gangzimo':'fulou';after.game!.turnSeat=1;after.game!.players[1].melds=[meld];after.game!.players[0].discards=[variant==='yonma'?'p0-':'p0+'];
 return {before,after};
}
describe('accepted public calls',()=>{
 it('names exact red claimed river event using engine marker convention',()=>{const {before,after}=pair();expect(acceptedPublicCallEvent(before,after)).toMatchObject({kind:'append',seat:1,index:0,meld:'p550-',tile:'p0',source:{seat:0,index:0,id:'discard:r:g:1:0:0'}})});
 it('uses sanma predecessor and inverse direction',()=>{const {before,after}=pair('p550-','sanma');expect(acceptedPublicCallEvent(before,after)?.source?.seat).toBe(0)});
 it.each(['version','room','hand','game','viewer','decision','settlement','turn'])('rejects unproved %s continuity',reason=>{const {before,after}=pair();if(reason==='version')after.version++;if(reason==='room')after.id='other';if(reason==='hand')after.game!.handId=2;if(reason==='game')after.game!.gameInstanceId='x';if(reason==='viewer')after.mySeat=2;if(reason==='decision')after.game!.decisionId='a';if(reason==='settlement')after.game!.settlement={} as never;if(reason==='turn')after.game!.turnSeat=2;expect(acceptedPublicCallEvent(before,after)).toBeNull()});
 it('emphasizes accepted group without guessing a missing or mismatched public source',()=>{for(const tile of ['p5','p0-']){const {before,after}=pair();before.game!.players[0].discards=[tile];after.game!.players[0].discards=[tile];expect(acceptedPublicCallEvent(before,after)?.source).toBeUndefined();expect(acceptedPublicCallEvent(before,after)?.seat).toBe(1)}});
 it('rejects another public action or multiple group changes',()=>{const {before,after}=pair();after.game!.players[2].melds=['s111-'];expect(acceptedPublicCallEvent(before,after)).toBeNull()});
 it('does not replay a quiet snapshot or initial baseline',()=>{const {after}=pair();expect(acceptedPublicCallEvent(null,after)).toBeNull();expect(acceptedPublicCallEvent(after,{...after,version:3})).toBeNull()});
 it('distinguishes accepted kakan added layer without old river transfer',()=>{const {before,after}=pair('p111-1');before.game!.phase='gang';before.game!.turnSeat=1;before.game!.players[1].melds=['p111-'];before.game!.players[0].discards=['p1+'];after.game!.players[0].discards=['p1+'];expect(acceptedPublicCallEvent(before,after)).toMatchObject({kind:'kakan',seat:1,index:0,tile:'p1'});expect(acceptedPublicCallEvent(before,after)?.source).toBeUndefined()});
 it('ankan has no supplying tile source',()=>{const {before,after}=pair('p5550');before.game!.phase='zimo';before.game!.turnSeat=1;before.game!.players[0].discards=[];after.game!.players[0].discards=[];expect(acceptedPublicCallEvent(before,after)).toMatchObject({kind:'append',seat:1});expect(acceptedPublicCallEvent(before,after)?.source).toBeUndefined()});
 it('invalid encoding and wrong kakan prefix are rejected',()=>{for(const meld of ['p55-0','p111+1']){const {before,after}=pair(meld);before.game!.players[1].melds=['p111-'];expect(acceptedPublicCallEvent(before,after)).toBeNull()}});
});
it.each(['+','='] as const)('proves exact source seat for yonma %s',marker=>{const before={id:'r',variant:'yonma',status:'playing',version:1,mySeat:0,game:{gameInstanceId:'g',handId:1,decisionId:'a',phase:'dapai',turnSeat:marker==='+'?2:3,settlement:null,players:[0,1,2,3].map(seat=>({seat,melds:[],discards:seat===(marker==='+'?2:3)?['s0']:[]}))}} as unknown as RoomView;const after=structuredClone(before);after.version++;after.game!.decisionId='b';after.game!.phase='fulou';after.game!.turnSeat=1;after.game!.players[1].melds=[`s550${marker}`];after.game!.players[marker==='+'?2:3].discards=[`s0${marker}`];expect(acceptedPublicCallEvent(before,after)?.source?.seat).toBe(marker==='+'?2:3)});
it('exact face mismatch falls back without normalizing red',()=>{const before={id:'r',variant:'yonma',status:'playing',version:1,mySeat:0,game:{gameInstanceId:'g',handId:1,decisionId:'a',phase:'dapai',turnSeat:0,settlement:null,players:[0,1,2,3].map(seat=>({seat,melds:[],discards:seat===0?['p5']:[]}))}} as unknown as RoomView;const after=structuredClone(before);after.version++;after.game!.decisionId='b';after.game!.phase='fulou';after.game!.turnSeat=1;after.game!.players[1].melds=['p550-'];after.game!.players[0].discards=['p5-'];expect(acceptedPublicCallEvent(before,after)?.source).toBeUndefined();expect(acceptedPublicCallEvent(before,after)?.tile).toBe('p0')});
it('cannot claim the caller own river as its supplying source',()=>{const {before,after}=pair();before.game!.turnSeat=1;before.game!.players[0].discards=[];before.game!.players[1].discards=['p0'];after.game!.players[0].discards=[];after.game!.players[1].discards=['p0-'];expect(acceptedPublicCallEvent(before,after)?.source).toBeUndefined()});
