import {expect,it} from 'vitest';
import {discardWaits} from '@/components/mahjong/discard-waits';
import type {GameView} from '@/modules/mahjong/types';
const tiles=(s:string)=>[...s.matchAll(/([mpsz])(\d+)/g)].flatMap(m=>[...m[2]].map(n=>m[1]+n));
function view(hand='p123456789s123z11'):GameView{return {decisionId:'d',phase:'zimo',roundWind:0,roundNumber:1,honba:0,riichiSticks:0,remainingTiles:30,doraIndicators:['z7'],turnSeat:0,hand:tiles(hand),drawnTile:'z1',players:[0,1,2,3].map(seat=>({seat,wind:seat,score:25000,handCount:13,discards:[],melds:[],riichi:false})),choices:[{id:'d:z1',type:'discard',value:'z1_'},{id:'r:z1',type:'riichi',value:'z1_'}],settlement:null,ranking:null}}
it('previews only offered discards and preserves the view',()=>{const g=view(),before=structuredClone(g);expect(discardWaits(g,0,'yonma','d:z1')).toEqual([{tile:'z1',remaining:2}]);expect(discardWaits(g,0,'yonma','r:z1')).toEqual([{tile:'z1',remaining:2}]);expect(g).toEqual(before);expect(discardWaits(g,0,'yonma','unknown')).toEqual([])});
it('does not mistake shape waits for an available live-wall count',()=>{const g=view();g.players[1].discards=['z1'];g.players[2].discards=['z1*'];expect(discardWaits(g,0,'yonma','d:z1')).toEqual([{tile:'z1',remaining:0}])});
it('counts called tiles once through the public meld',()=>{const g=view();g.players[1].discards=['z1-'];g.players[2].melds=['z111-'];expect(discardWaits(g,0,'yonma','d:z1')[0].remaining).toBe(0)});
it('handles an open hand and a closed kan without changing their shape',()=>{for(const meld of ['p111-','p1111']){const g=view('s123456789z11');g.players[0].melds=[meld];expect(discardWaits(g,0,'yonma','d:z1')).toEqual([{tile:'z1',remaining:2}])}});
it('normalizes exposed red fives and counts dora indicators',()=>{const g=view('p123456789s123p55');g.choices=[{id:'red',type:'discard',value:'p5'}];g.players[1].discards=['p0'];g.doraIndicators=['p5'];expect(discardWaits(g,0,'yonma','red').find(w=>w.tile==='p5')?.remaining).toBe(0)});
it('filters absent middle manzu in three-player waits',()=>{const g=view('p123456789s123m23');g.choices=[{id:'m3',type:'discard',value:'m3'}];expect(discardWaits(g,0,'yonma','m3')).toEqual([{tile:'m2',remaining:3}]);expect(discardWaits(g,0,'sanma','m3')).toEqual([])});
it('counts extracted north as public physical tiles',()=>{const g=view('p123456789s123z44');g.choices=[{id:'north',type:'discard',value:'z4'}];g.players[1].nuki=2;expect(discardWaits(g,0,'sanma','north')).toEqual([{tile:'z4',remaining:0}])});
it('returns no preview for non-tenpai, invalid shape, results or another seat',()=>{const g=view('p147s258m369z12345');expect(discardWaits(g,0,'yonma','d:z1')).toEqual([]);g.settlement={kind:'draw',name:'荒牌',yaku:[],delta:[0,0,0,0],uraIndicators:[]};expect(discardWaits(g,0,'yonma','d:z1')).toEqual([]);expect(discardWaits(view(),9,'yonma','d:z1')).toEqual([])});
