// @vitest-environment jsdom
import {act,cleanup,renderHook} from '@testing-library/react';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {handClickPreference,useHandHover} from '@/components/mahjong/use-hand-hover';
beforeEach(()=>{vi.useFakeTimers();localStorage.clear();});
afterEach(()=>{cleanup();vi.useRealTimers();localStorage.clear();});
const selection={tileId:'hand:1:p0',choiceId:'native-red-copy'};
function mount(){const onSelect=vi.fn(),onClear=vi.fn();const view=renderHook(({scope,disabled})=>useHandHover({scope,disabled,onSelect,onClear}),{initialProps:{scope:'a',disabled:false}});return {...view,onSelect,onClear};}
it('strictly waits more than ten milliseconds and never submits anything',()=>{const v=mount();act(()=>v.result.current.enter(selection));act(()=>vi.advanceTimersByTime(10));expect(v.onSelect).not.toHaveBeenCalled();act(()=>vi.advanceTimersByTime(1));expect(v.onSelect).toHaveBeenCalledExactlyOnceWith(selection);});
it('a mouse press before dwell freezes an unselected tile',()=>{const v=mount();act(()=>v.result.current.enter(selection));act(()=>vi.advanceTimersByTime(5));act(()=>v.result.current.press('mouse'));act(()=>vi.advanceTimersByTime(100));expect(v.onSelect).not.toHaveBeenCalled();});
it('a mouse press preserves an already selected tile for the click',()=>{const v=mount();act(()=>v.result.current.enter(selection));act(()=>vi.advanceTimersByTime(11));act(()=>v.result.current.press('mouse'));act(()=>v.result.current.leave());expect(v.onClear).not.toHaveBeenCalled();});
it('touch cannot inherit the mouse hover selection',()=>{const v=mount();act(()=>v.result.current.enter(selection));act(()=>vi.advanceTimersByTime(11));act(()=>v.result.current.press('touch'));expect(v.onClear).toHaveBeenCalledOnce();});
it('leaving before dwell cancels selection',()=>{const v=mount();act(()=>v.result.current.enter(selection));act(()=>v.result.current.leave());act(()=>vi.advanceTimersByTime(100));expect(v.onSelect).not.toHaveBeenCalled();});
it('leaving after dwell clears only hover-owned selection',()=>{const v=mount();act(()=>v.result.current.enter(selection));act(()=>vi.advanceTimersByTime(11));act(()=>v.result.current.leave());expect(v.onClear).toHaveBeenCalledOnce();act(()=>v.result.current.leave());expect(v.onClear).toHaveBeenCalledOnce();});
it('moving across two identical tile copies settles only the last native instance',()=>{const v=mount();act(()=>v.result.current.enter(selection));act(()=>vi.advanceTimersByTime(8));act(()=>v.result.current.enter({...selection,tileId:'hand:2:p0'}));act(()=>vi.advanceTimersByTime(11));expect(v.onSelect).toHaveBeenCalledExactlyOnceWith({...selection,tileId:'hand:2:p0'});});
it.each(['scope','disabled'])('changing %s invalidates pending hover',kind=>{const v=mount();act(()=>v.result.current.enter(selection));v.rerender({scope:kind==='scope'?'b':'a',disabled:kind==='disabled'});act(()=>vi.advanceTimersByTime(100));expect(v.onSelect).not.toHaveBeenCalled();});
it('unmount cancels the timer without notifying a retired component',()=>{const v=mount();act(()=>v.result.current.enter(selection));v.unmount();act(()=>vi.advanceTimersByTime(100));expect(v.onSelect).not.toHaveBeenCalled();expect(v.onClear).not.toHaveBeenCalled();});
it.each(['blur','pagehide','resize','orientationchange','fullscreenchange'])('%s clears pending and lifted hover',event=>{const v=mount();act(()=>v.result.current.enter(selection));act(()=>window.dispatchEvent(new Event(event)));act(()=>vi.advanceTimersByTime(100));expect(v.onSelect).not.toHaveBeenCalled();act(()=>v.result.current.enter(selection));act(()=>vi.advanceTimersByTime(11));act(()=>window.dispatchEvent(new Event(event)));expect(v.onClear).toHaveBeenCalledOnce();});
it('optional desktop two-click preference persists and disables hover selection',()=>{const v=mount();act(()=>v.result.current.toggle());expect(localStorage.getItem(handClickPreference)).toBe('1');act(()=>v.result.current.enter(selection));act(()=>vi.advanceTimersByTime(100));expect(v.onSelect).not.toHaveBeenCalled();v.unmount();const restored=mount();expect(restored.result.current.twoClicks).toBe(true);act(()=>restored.result.current.toggle());expect(localStorage.getItem(handClickPreference)).toBe('0');});
it('a disabled table never preselects',()=>{const v=mount();v.rerender({scope:'a',disabled:true});act(()=>v.result.current.enter(selection));act(()=>vi.advanceTimersByTime(100));expect(v.onSelect).not.toHaveBeenCalled();});
