// @vitest-environment jsdom
import {act,cleanup,fireEvent,render,screen} from '@testing-library/react';
import {useRef} from 'react';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {usePublicCallMotion} from '@/components/mahjong/use-public-call-motion';
import {DiscardFlightLayer} from '@/components/mahjong/use-discard-motion';
import {MahjongMeld} from '@/components/mahjong/mahjong-meld';
import type {RoomView} from '@/modules/mahjong/types';
const before={id:'r',variant:'yonma',status:'playing',version:1,mySeat:0,game:{gameInstanceId:'g',handId:1,decisionId:'a',phase:'dapai',turnSeat:0,settlement:null,players:[0,1,2,3].map(seat=>({seat,discards:seat===0?['p0']:[],melds:[]}))}} as unknown as RoomView;
const after=structuredClone(before);after.version=2;after.game!.phase='fulou';after.game!.turnSeat=1;after.game!.decisionId='b';after.game!.players[0].discards=['p0-'];after.game!.players[1].melds=['p550-'];
let animations:any[]=[];let hidden=false;let offset=0;
beforeEach(()=>{vi.stubGlobal('matchMedia',()=>({matches:false,addEventListener:()=>{},removeEventListener:()=>{}}));vi.spyOn(Element.prototype,'getBoundingClientRect').mockImplementation(function(this:HTMLElement){const x=this.closest('[data-discard-event-id]')?10+offset:300;return {left:x,top:20,width:20,height:30,right:x+20,bottom:50,x,y:20} as DOMRect});Object.defineProperty(Element.prototype,'animate',{configurable:true,value:function(this:HTMLElement,frames:any,options:any){const a={id:'',onfinish:null,cancel:vi.fn()};animations.push({target:this,frames,options,a});return a}})});
afterEach(()=>{cleanup();vi.restoreAllMocks();vi.unstubAllGlobals();delete (Element.prototype as any).animate;animations=[];hidden=false;offset=0});
function Harness({room,connected=true,canAnimate=true,hideActiveDiscard=false}:{room:RoomView,connected?:boolean,canAnimate?:boolean,hideActiveDiscard?:boolean}){const tableRef=useRef<HTMLDivElement>(null);const motion=usePublicCallMotion({room,ownSeat:0,connected,canAnimate,tableRef});return <><div ref={tableRef}>{room.game!.players[0].discards[0]==='p0'?<span className={hideActiveDiscard?'is-discard-motion-hidden':''} data-discard-event-id="discard:r:g:1:0:0" style={{visibility:hidden?'hidden':'visible'}}><span className="mahjong-tile"/></span>:null}{room.game!.players[1].melds.map((meld,index)=><MahjongMeld key={index} meld={meld} seat={1} index={index}/>)}<button onClick={motion.cancel}>input</button></div>{motion.flight?<DiscardFlightLayer kind="call" flight={motion.flight} onFinish={motion.finishFlight}/>:null}</>}
it('holds only exact called red face and keeps finite emphasis through quiet updates',()=>{const ui=render(<Harness room={before}/>);ui.rerender(<Harness room={after}/>);expect(screen.getByTestId('mahjong-call-flight')).toBeTruthy();const target=document.querySelector<HTMLElement>('[data-called] .mahjong-tile')!;expect(target.style.visibility).toBe('hidden');expect(document.querySelector('[data-called]')?.getAttribute('data-tile-value')).toBe('p0');const emphasis=animations.find(a=>a.options.duration===900);expect(emphasis.target.dataset.meldSeat).toBe('1');ui.rerender(<Harness room={{...after,version:3}} canAnimate={false}/>);expect(animations.filter(a=>a.options.duration===900)).toHaveLength(1);act(()=>animations.find(a=>a.options.duration===230).a.onfinish());expect(target.style.visibility).toBe('');expect(screen.queryByTestId('mahjong-call-flight')).toBeNull();expect(emphasis.a.cancel).not.toHaveBeenCalled();act(()=>emphasis.a.onfinish());expect(emphasis.a.cancel).toHaveBeenCalled()});
it.each(['hidden','missing'])('falls back to group emphasis for %s source',mode=>{hidden=mode==='hidden';const initial=structuredClone(before);if(mode==='missing')initial.game!.players[0].discards=[];const final=structuredClone(after);if(mode==='missing')final.game!.players[0].discards=[];const ui=render(<Harness room={initial}/>);ui.rerender(<Harness room={final}/>);expect(screen.queryByTestId('mahjong-call-flight')).toBeNull();expect(animations.filter(a=>a.options.duration===900)).toHaveLength(1);expect(document.querySelector<HTMLElement>('[data-called] .mahjong-tile')!.style.visibility).toBe('')});
it.each(['input','disconnect','resize','unmount','decision','scope','settlement','hidden'])('restores held target on %s',reason=>{const ui=render(<Harness room={before}/>);ui.rerender(<Harness room={after}/>);const target=document.querySelector<HTMLElement>('[data-called] .mahjong-tile')!;expect(target.style.visibility).toBe('hidden');if(reason==='input')fireEvent.click(screen.getByText('input'));if(reason==='disconnect')ui.rerender(<Harness room={after} connected={false}/>);if(reason==='resize')fireEvent(window,new Event('resize'));if(reason==='unmount')ui.unmount();if(reason==='scope')ui.rerender(<Harness room={{...after,id:'other'}}/>);if(reason==='settlement')ui.rerender(<Harness room={{...after,game:{...after.game!,settlement:{kind:'draw',name:'draw',delta:[],yaku:[],uraIndicators:[]}}}}/>);if(reason==='hidden'){vi.spyOn(document,'visibilityState','get').mockReturnValue('hidden');fireEvent(document,new Event('visibilitychange'));}if(reason==='decision')ui.rerender(<Harness room={{...after,version:3,game:{...after.game!,decisionId:'c'}}}/>);expect(target.style.visibility).toBe('');expect(screen.queryByTestId('mahjong-call-flight')).toBeNull()});
it('does not replay hydration, coalesced or reconnect snapshots',()=>{const ui=render(<Harness room={before} connected={false}/>);ui.rerender(<Harness room={after}/>);expect(screen.queryByTestId('mahjong-call-flight')).toBeNull();ui.rerender(<Harness room={before}/>);ui.rerender(<Harness room={{...after,version:3}}/>);expect(screen.queryByTestId('mahjong-call-flight')).toBeNull();ui.rerender(<Harness room={before}/>);ui.rerender(<Harness room={after} canAnimate={false}/>);expect(screen.queryByTestId('mahjong-call-flight')).toBeNull()});
it.each(['ankan','kakan'])('emphasizes real accepted %s group without a river flight',kind=>{const b=structuredClone(before),a=structuredClone(after);b.game!.phase=kind==='kakan'?'gang':'zimo';b.game!.turnSeat=1;b.game!.players[0].discards=[];a.game!.players[0].discards=[];a.game!.phase='gangzimo';if(kind==='kakan')b.game!.players[1].melds=['p111-'];a.game!.players[1].melds=[kind==='kakan'?'p111-1':'p4444'];const ui=render(<Harness room={b}/>);ui.rerender(<Harness room={a}/>);expect(screen.queryByTestId('mahjong-call-flight')).toBeNull();expect(animations.filter(a=>a.options.duration===900)).toHaveLength(1);if(kind==='kakan')expect(document.querySelector('[data-layer="added"]')?.getAttribute('data-tile-value')).toBe('p1')});
it('invalidates source before resize acceptance until refreshed geometry is available',()=>{const ui=render(<Harness room={before}/>);fireEvent(window,new Event('resize'));ui.rerender(<Harness room={after}/>);expect(screen.queryByTestId('mahjong-call-flight')).toBeNull();expect(animations.filter(a=>a.options.duration===900)).toHaveLength(1)});

it('retains an active hidden discard source until its accepted call consumes it',()=>{const ui=render(<Harness room={before}/>);ui.rerender(<Harness room={before} hideActiveDiscard/>);ui.rerender(<Harness room={after}/>);expect(screen.getByTestId('mahjong-call-flight')).toBeTruthy();const volume=document.querySelector<HTMLElement>('[data-meld-volume]')!;const target=document.querySelector<HTMLElement>('[data-called] .mahjong-tile')!;expect(volume.style.visibility).toBe('hidden');expect(target.style.visibility).toBe('hidden');const movement=animations.find(a=>a.options.duration===230);expect(movement).toBeTruthy();act(()=>movement.a.onfinish());expect(screen.queryByTestId('mahjong-call-flight')).toBeNull();expect(volume.style.visibility).toBe('');expect(target.style.visibility).toBe('')});
